#!/bin/bash

# Manually listed to keep track of things
togather=( \
~/.config/nvim/init.vim \
~/.config/nvim/cfg \
~/.config/nvim/coc-settings.json \
)

for f in ${togather[@]}; do
    cp -r $f .
done
